### ISSUE TITLE
Python versions and dependencies.

### ISSUE THREAD

**Issue by ojeda-e** [patrickfuchs/buildH#151]
The [Requirements](https://github.com/patrickfuchs/buildH#requirements) section in the README says:

> buildH is written in Python 3 and needs the modules numpy, pandas, MDAnalysis and Numba.

- Is there a way to know the minimum versions of the dependencies? 
- numpy -> NumPy.

> Python >= 3.6 and <= 3.8 is mandatory for running buildH
- Since the repo doesn't include CI, out of curiosity, how did you identify Python 3.6 as min and 3.8 as max versions?

**Comment by pierrepo** [comment]
Hi @ojeda-e 

> Is there a way to know the minimum versions of the dependencies?

Not for all. However, MDAnalysis is the strongest dependency. We need MDAnalysis version >= 1.1.1 due to some annoying warning messages in previous versions. MDAnalysis itself requires [NumPy >= 1.16.0](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py).

> Since the repo doesn't include CI, out of curiosity, how did you identify Python 3.6 as min and 3.8 as max versions?

We have a CI as GitHub actions, see for instance in the `.github/workflows` directory.

We need Python 3.6 because we are using f-strings and Python <= 3.8 is a requirement of MDAnalysis 1.1.1. However, MDAnalysis 2.0.0 has been released a week ago and is compatible from Python 3.6 to Python 3.9. We might test compatibility with MDanalysis 2.0.0.

**Comment by patrickfuchs** [comment]
With the new version 1.6.0 just released, buildH is now fully compatible with MDAnalysis 2.0.0 and Python 3.9.

**Comment by ojeda-e** [comment]
Thanks for your answers, @pierrepo @patrickfuchs. 
I missed your CI, my apologies. I see the tests for Python 3.6, 3.7, 3.8, and 3.9. I also found minimum versions of dependencies in the [documentation](https://buildh.readthedocs.io/en/latest/installation.html), which makes everything more clear. 
Thanks for adding these changes.
