### ISSUE TITLE
CH3 groups

### ISSUE THREAD

**Issue by ohsOllila** [patrickfuchs/buildH#157]
I have been finally able to come back to united atom simulations and their quality evaluation in the NMRlipids project.

While doing this I encountered again to the issue of order parameter of CH3 groups. The hydrogen positions for these groups are not uniquely defined in united atom models, and therefore the resulting order parameters for these groups are not reasonable. This is a practical problem in NMRlipids quality evaluation codes which compare these values to experiments. 

In the current default def files the atoms for CH3 groups are defined. In my opinion, it might be better to remove those because order parameters for these segments from united atom models are not realistic.

**Comment by patrickfuchs** [comment]
Thank you for your comment @ohsOllila. Indeed we cannot know the CH3 rotation, so I'm not surprised the reconstructed C-H don't give correct order parameters (OP). However, I would think that the mean OP over the 3 reconstructed C-H should be correct, is it? If yes, maybe we could write this mean OP in the output?
Even if the reconstruction doesn't give correct OP for CH3, I think this still would be nice if buildH continue to reconstruct them in case a user wants an output with H (pdb or xtc). But we can decide not to write them in the OP output by default. Maybe we can put a flag if the user wants them in the output, so that we can also add some warnings about their accuracy.

**Comment by ohsOllila** [comment]
I have not checked the average order parameters.

The issue from the NMRlipids databank point of view is that the quality evaluation takes all the order parameters and automatically compares to experiments, which indeed does not make sense for CH3 hydrogens. From our point of view the easiest solution would be not to calculate those at all. So from our point of view, the flag option would work out well.

**Comment by HubLot** [comment]
To follow up on this issue, the idea will be to add a flag `--ignore-CH3s` to prevent `buildH` to calculate OP.

More precisely, `init_dic_OP` will be modified to take as argument the full `dic_lipid` dict and this flag and don't create the key of `dic_op` (dictionary of results) when the OP is part of a CH3.

```python

#pseudo code
def init_dic_OP(universe_woH, dic_atname2genericname, dic_lipid, ign_CH3s):
    ...
    for key in dic_atname2genericname:
    carbon, _ = key
    if not( ign_CH3s and dic_lipid[carbon][0] == 'CH3'): 
        dic_OP[key] = [[] for _ in range(nb_residus)]
    ...

**Comment by patrickfuchs** [comment]
Thanks a lot @HubLot 👍 We will try to implement this early january.

**Comment by ohsOllila** [comment]
> All right, we'll try to implement that flag. It shouldn't take too long, but when would you need that?

Thanks. We would use it as soon as it is available.

**Comment by patrickfuchs** [comment]
> Thanks. We would use it as soon as it is available.

All right, we plan to do that early january 2022, we'll make you know.

**Comment by patrickfuchs** [comment]
> Thanks. We would use it as soon as it is available.

@ohsOllila, the option `-igch3` is now implemented to the command line and it is fully functionnal. It is also usable in a module mode with the option `ignore_CH3s`: `buildh.launch(..., ignore_CH3s=True)`. Don't hesitate to post an issue (or reopen that one) if something goes wrong or if you need anything else.

Since this new option is implemented, I close this issue.
